.TH MNCOMMON 3 "2012 Sep" "mncommon" "User Libraries"
.SH NAME
mncommon - My common utilities
.SH SYNOPSIS
.BR
.nf
\&#include <mncommon/array.h>
\&#include <mncommon/list.h>
.SH LIST OF FUNCTIONS
.BR
.SH SEE ALSO
.BR
.SH HISTORY
.BR
.SH BUGS
.BR
.SH AUTHORS
.BR
.\".Dd Sep 2012
.\".Dt mncommon 3
.\".Os
.\".Sh NAME
.\".Nm mncommon
.\".Nd My common utilities.
.\".Sh LIBRARY
.\".Lb libmncommon
.\".Sh SYNOPSIS
.\".In mncommon/array.h
.\".In mncommon/list.h
.\".Sh DESCRIPTION
.\".Pp
.\".Sh LIST OF FUNCTIONS
.\".Pp
.\".Sh SEE ALSO
.\".Pp
.\".Sh HISTORY
.\".Pp
.\".Sh BUGS
.\".Pp
.\".Sh AUTHORS
.\".Pp
