.TH MRKCOMMON 3 "2012 Sep" "mrkcommon" "User Libraries"
.SH NAME
mrkcommon - My common utilities
.SH SYNOPSIS
.BR
.nf
\&#include <mrkcommon/array.h>
\&#include <mrkcommon/list.h>
.SH LIST OF FUNCTIONS
.BR
.SH SEE ALSO
.BR
.SH HISTORY
.BR
.SH BUGS
.BR
.SH AUTHORS
.BR
.\".Dd Sep 2012
.\".Dt MRKCOMMON 3
.\".Os
.\".Sh NAME
.\".Nm mrkcommon
.\".Nd My common utilities.
.\".Sh LIBRARY
.\".Lb libmrkcommon
.\".Sh SYNOPSIS
.\".In mrkcommon/array.h
.\".In mrkcommon/list.h
.\".Sh DESCRIPTION
.\".Pp
.\".Sh LIST OF FUNCTIONS
.\".Pp
.\".Sh SEE ALSO
.\".Pp
.\".Sh HISTORY
.\".Pp
.\".Sh BUGS
.\".Pp
.\".Sh AUTHORS
.\".Pp
