#!/bin/sh

#aclocal
#autoheader
#autoreconf
#automake --add-missing
#libtoolize
make distclean
autoreconf
./configure --prefix=$HOME --enable-debug
make

# Before checking in to git: don't forget to update the port.
# autoreconf
# make dist
# cp mrkcommon-0.1.tar.gz /usr/data/distfiles
# cd /usr/data/distfiles && git commit a -m update && git push
# cd ports && [manually make sum from /usr/data/distfiles/mrkcommon-0.1.tar.gz]
