#!/bin/sh

# On FreeBSD:
#   pkg install autotools
#
# On Linux:
#   apt-get update
#   apt-get install autotools-dev autoconf libtool
#   or apt-get install build-essential
#
#   yum install epel-release
#   yum group install "Development Tools"
#   yum install openssl-devel zlib-devel libev-devel
#
# Git setup:
#   git init
#   git add \
#     .gitignore \
#     AUTHORS \
#     COPYING \
#     ChangeLog \
#     Makefile.am \
#     NEWS \
#     README \
#     configure.ac \
#     man/Makefile.am \
#     setup-env \
#     src/${pname}.c \
#     src/${pname}.h \
#     src/${pname}_private.h \
#     src/Makefile.am \
#     src/diag.txt \
#     test/Makefile.am \
#     test/diag.txt \
#     test/gendata.c \
#     test/runscripts \
#     test/testbar.c \
#     test/testfoo.c \
#     test/unittest.h
uname_s=`uname -s`

sha256_cmd=/sbin/sha256
if test "$uname_s" = "Linux"
then
    linux_exclusions='--enable-conf=no'
    sha256_cmd=/usr/bin/sha256sum
elif test "$uname_s" = "Darwin"
then
    linux_exclusions='--enable-memdebug=no'
fi

if test "$1" = "init"
then
    export LDFLAGS=-L$HOME/lib
    export CFLAGS=-I$HOME/include

    autoreconf --force
    aclocal
    autoheader
    autoreconf
    automake --add-missing
    libtoolize
    make distclean
    autoreconf
    ./configure --prefix=$HOME --enable-debug $linux_exclusions $MN_CONFIGURE_ARGS

elif test "$1" = "dev"
then
    export LDFLAGS=-L$HOME/lib
    export CFLAGS=-I$HOME/include
    autoreconf --force
    ./configure --prefix=$HOME --enable-debug $linux_exclusions $MN_CONFIGURE_ARGS

elif test "$1" = "dev-memdebug"
then
    export LDFLAGS=-L$HOME/lib
    export CFLAGS="-I$HOME/include -DDO_MEMDEBUG"
    autoreconf --force
    ./configure --prefix=$HOME --enable-debug $linux_exclusions $MN_CONFIGURE_ARGS

elif test "$1" = "dev-ndebug"
then
    export LDFLAGS=-L$HOME/lib
    export CFLAGS=-I$HOME/include
    autoreconf --force
    ./configure --prefix=$HOME $linux_exclusions $MN_CONFIGURE_ARGS

elif test "$1" = "dist"
then
    unset LDFLAGS
    unset CFLAGS
    autoreconf --force
    ./configure --enable-profile=no $linux_exclusions $MN_CONFIGURE_ARGS
    make dist
    if test -f port/distinfo
    then
        truncate -s0 port/distinfo
    fi
    for i in *.tar.gz
    do
        cp -v $i /data2/mkushnir/distfiles/
        if test -f port/distinfo
        then
            $sha256_cmd $i >port/distinfo
            echo "SIZE ($i) = `stat -f%z $i`" >>port/distinfo
        fi
    done
elif test "$1" = "du"
then
    find . -type f -name '*.[ch]' -ls | awk '{print $7;}' | (n=0; while read a; do n=$((n + a)); done; echo $n)
else
    echo "`basename $0` {init|dev|dist|dev-ndebug|dev-memdebug|du}"
fi
