# $FreeBSD$
PORTNAME=	mrkcommon
PORTVERSION=	0.1
CATEGORIES=	devel
MASTER_SITES=	https://raw.github.com/mkushnir/distfiles/master/

MAINTAINER=	markiyan.kushnir@gmail.com
COMMENT=	Markiyan\'s library of common C functions

MAN3=		mrkcommon.3
MANCOMPRESSED=	yes
USE_LDCONFIG=	yes


GNU_CONFIGURE=	yes

.include <bsd.port.mk>
