#ifndef DIAG_N
#define DIAG_H
/* Autogenerated by gen-diag. */
#include <stdlib.h>
#define DIAG_CLASS_MASK 0xffffff00
#define DIAG_CLASS_SHL 8
struct _diag_entry_st {int cls; const char *fmt;};
extern struct _diag_entry_st diag_table[];
const char *diag_str(int);
int diag_class(unsigned, unsigned);
#define FAIL(s) do { perror(s); abort(); } while (0)
#define DIAG_NOERROR (0<<DIAG_CLASS_SHL)
#define ARRAY_CLEAR_ITEM (1<<DIAG_CLASS_SHL)
#define ARRAY_DECR (2<<DIAG_CLASS_SHL)
#define ARRAY_ENSURE_LEN (3<<DIAG_CLASS_SHL)
#define ARRAY_FIND (4<<DIAG_CLASS_SHL)
#define ARRAY_INCR (5<<DIAG_CLASS_SHL)
#define ARRAY_INIT (6<<DIAG_CLASS_SHL)
#define ARRAY_SORT (7<<DIAG_CLASS_SHL)
#define CONF_INIT (8<<DIAG_CLASS_SHL)
#define CONF_PARSER_NEXT_TOK (9<<DIAG_CLASS_SHL)
#define CONF_PARSE_BUF (10<<DIAG_CLASS_SHL)
#define CONF_PARSE_FILE (11<<DIAG_CLASS_SHL)
#define CONF_PARSE_FPATH (12<<DIAG_CLASS_SHL)
#define CONF_PARSE_HANDLER_WRAPPER (13<<DIAG_CLASS_SHL)
#define DLIST_INIT (14<<DIAG_CLASS_SHL)
#define LIST_CLEAR_ITEM (15<<DIAG_CLASS_SHL)
#define LIST_DECR (16<<DIAG_CLASS_SHL)
#define LIST_ENSURE_LEN (17<<DIAG_CLASS_SHL)
#define LIST_FIND (18<<DIAG_CLASS_SHL)
#define LIST_INCR (19<<DIAG_CLASS_SHL)
#define LIST_INIT_ (20<<DIAG_CLASS_SHL)
#define LIST_REINIT (21<<DIAG_CLASS_SHL)
#endif
